name: Deploy to Azure Web App

on:
  push:
    branches:
      - entra-auth
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  dev-deploy:
    permissions:
      id-token: write   # Add this permission
      contents: read
    uses: ./.github/workflows/entraid_web_deployment.yml
    with:
      environment: 'dev'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  test-deploy:
    uses: ./.github/workflows/entraid_web_deployment.yml
    permissions:
      id-token: write   # Add this permission
      contents: read
    with:
      environment: 'test'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  prod-deploy:
    uses: ./.github/workflows/entraid_web_deployment.yml
    permissions:
      id-token: write   # Add this permission
      contents: read
    with:
      environment: 'prod'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}